import streamlit as st
from google import genai
from google.genai import types
import urllib.parse

# Page setup
st.set_page_config(page_title="Mana AI Image Creator", page_icon="🎨", layout="centered")

# CSS to hide all Streamlit watermarks & headers (as requested before)
st.markdown("""
    <style>
    header, [data-testid="stHeader"], .stDeployButton, #MainMenu { visibility: hidden !important; display: none !important; }
    footer, div[data-testid="stFooter"], .viewerBadge_container__1QSob { visibility: hidden !important; display: none !important; }
    h1 a, .stMarkdown h1 a, div[data-testid="stDecoration"], div[data-testid="stToolbar"] { display: none !important; }
    [data-testid="stBottomBlockContainer"] footer { display: none !important; }
    </style>
    """, unsafe_allow_html=True)

st.title("🎨 Mana AI Image Creator")

# API Setup
API_KEY = st.secrets["GEMINI_API_KEY"]
client = genai.Client(api_key=API_KEY)

if "messages" not in st.session_state:
    st.session_state.messages = []

# Show previous chat messages
for message in st.session_state.messages:
    with st.chat_message(message["role"]):
        st.markdown(message["content"])
        if "image_url" in message:
            st.image(message["image_url"], caption="Generated by Mana AI")

# User Input
if user_input := st.chat_input("Emaina adugu leda image generate cheyamanu brother..."):
    # Show user message
    with st.chat_message("user"):
        st.markdown(user_input)
    st.session_state.messages.append({"role": "user", "content": user_input})

    # Image Detection Logic
    img_keywords = ["image", "generate", "photo", "bomma", "picture", "create", "pic", "draw"]
    is_image_request = any(word in user_input.lower() for word in img_keywords)

    with st.chat_message("assistant"):
        try:
            if is_image_request:
                # 1. Gemini help tho oka super English prompt create cheyiddam
                prompt_task = f"Create a high-quality English image generation prompt for: {user_input}. Only give the prompt, nothing else."
                prompt_res = client.models.generate_content(model='gemini-2.0-flash', contents=prompt_task)
                refined_prompt = prompt_res.text.strip()
                
                # 2. Generate Image URL (Using Pollinations Magic - No API key needed for this)
                encoded_prompt = urllib.parse.quote(refined_prompt)
                image_url = f"https://pollinations.ai/p/{encoded_prompt}?width=1024&height=1024&seed=42&nologo=true"
                
                # 3. Display Result
                st.markdown(f"Sure brother! Idhigo nuvvu adigina image ready: \n\n *Prompt: {refined_prompt}*")
                st.image(image_url)
                
                # Save to session
                st.session_state.messages.append({
                    "role": "assistant", 
                    "content": f"Image generated for: {user_input}",
                    "image_url": image_url
                })
            else:
                # Normal Chat Logic
                config = types.GenerateContentConfig(
                    system_instruction="You are a friendly Telugu AI assistant. Reply in Tanglish. If the user wants an image, tell them to use words like 'generate' or 'image'. Use 'brother' often.",
                    temperature=0.7
                )
                response = client.models.generate_content(model='gemini-2.0-flash', contents=user_input, config=config)
                st.markdown(response.text)
                st.session_state.messages.append({"role": "assistant", "content": response.text})
                
        except Exception as e:
            st.error(f"Chinna problem anna: {str(e)}")
