import streamlit as st
import urllib.parse

# Page setup
st.set_page_config(page_title="Mana AI Image Creator", page_icon="🎨", layout="centered")

# CSS to hide all Streamlit watermarks & headers (100% Clean)
st.markdown("""
    <style>
    header, [data-testid="stHeader"], .stDeployButton, #MainMenu { visibility: hidden !important; display: none !important; }
    footer, div[data-testid="stFooter"], .viewerBadge_container__1QSob { visibility: hidden !important; display: none !important; }
    h1 a, .stMarkdown h1 a, div[data-testid="stDecoration"], div[data-testid="stToolbar"] { display: none !important; }
    [data-testid="stBottomBlockContainer"] footer { display: none !important; }
    </style>
    """, unsafe_allow_html=True)

st.title("🎨 Mana AI Image Creator")

if "messages" not in st.session_state:
    st.session_state.messages = []

# Show previous chat messages
for message in st.session_state.messages:
    with st.chat_message(message["role"]):
        st.markdown(message["content"])
        if "image_url" in message:
            # First show image
            st.image(message["image_url"], caption="Generated by Mana AI")
            # Then provide direct link below it as backup
            st.markdown(f"**🔗 Direct Image Link:** [Click here to view]({message['image_url']})")

# User Input
if user_input := st.chat_input("Emaina prompt type chey brother, image generate cheddham..."):
    # Show user message
    with st.chat_message("user"):
        st.markdown(user_input)
    st.session_state.messages.append({"role": "user", "content": user_input})

    with st.chat_message("assistant"):
        try:
            # DIRECT ENGINE: Gemini dependence rule zero! No API key required here.
            encoded_prompt = urllib.parse.quote(user_input)
            image_url = f"https://pollinations.ai/p/{encoded_prompt}?width=1024&height=1024&seed=50&nologo=true"
            
            # Display Result Immediately
            st.markdown(f"Sure brother! Idhigo nuvvu adigina image instant ga ready: 🔥")
            
            # Show image component
            st.image(image_url)
            
            # Show direct blue link as backup (THIS IS NEW)
            st.markdown(f"**🔗 Direct Image Link:** [Click here to view]({image_url})")
            
            # Save to session
            st.session_state.messages.append({
                "role": "assistant", 
                "content": f"Image generated for: {user_input}",
                "image_url": image_url
            })
                
        except Exception as e:
            st.error(f"Chinna problem anna: {str(e)}")
